[package]
name = "wazir-drop"
edition = "2021"

[dependencies]
rand = { version = "0.9.2", optional = true }

[workspace]
resolver = "3"
members = ["external-player", "gui", "random-player", "referee"]