[package]
name = "wazir-drop"
edition = "2021"

[workspace]
resolver = "3"
members = ["external-player", "extra", "gui", "random-player", "referee"]

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_results = "deny"

[workspace.lints.clippy]
default_trait_access = "deny"

[lints]
workspace = true