[package]
name = "wazir-drop"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9.2", optional = true }

[workspace]
resolver = "3"
members = ["gui", "random-player", "referee"]