num_cpus = 31
log_dir = "logs"

[player.caia1]
type = "External"
path = "../caia_install_zeropointone/games/zeropointone/bin/player1"

[player.caia2]
type = "External"
path = "../caia_install_zeropointone/games/zeropointone/bin/player2"

[player.caia3]
type = "External"
path = "../caia_install_zeropointone/games/zeropointone/bin/player3"

[player.random]
type = "Random"

[player.main]
type = "Main"

[player.wazir-drop]
type = "External"
path = "target/release/wazir-drop"

[[match]]
players = ["wazir-drop", "caia3"]
opening_length = 0
num_rounds = 10000
