log = "logs/export.log"

[[command]]
type = "export"
weights = "data/nnue6_160_16_32.weights"
output = "data/nnue_weights.rs"
features = "WPS"

[command.model.nnue.config]
embedding_size = 160
hidden_sizes = [16, 32]
hidden_weight_bits = [8, 6]
value_scale = 10000
