log = "logs/export.log"

[command.export]
weights = "data/linear_ps_2.weights"
output = "data/linear_ps_weights.rs"
features = "PS"
value_scale = 1000

[command.export.model.linear]
# doesn't matter
learning_rate = 1e-3
weight_decay = 0
