log = "logs/export.log"

[[command]]
type = "export"
weights = "data/nnue.weights"
output = "data/nnue_wps_weights.rs"
features = "WPS"

[command.model.nnue.config]
embedding_size = 64
hidden_sizes = []
hidden_weight_bits = 6
value_scale = 10000
