log = "logs/export.log"

[command.export]
weights = "data/linear_ps_1.weights"
output = "data/linear_ps_weights.rs"
features = "PS"
value_scale = 1000

[command.export.model.linear]
learning_rate = 1e-3  # doesn't matter
