log = "data/openings3.log"
openings_file = "data/openings3.txt"
export_book = "data/book_data3.rs"
cpus = 60
ttable_size_mb = 64
pvtable_size_mb = 2
seed = 1234
sample_size = 10000
sample_iterations = 5
reasonable_size = 25000
depth = 10000
book_size = 20000
extra_depth_book_size = [8000, 3500, 1500, 600, 180, 60]
block = 1000
log_period_seconds = 60
