log = "logs/openings1.log"
openings_file = "data/openings1.txt"
export_book = "data/book_data1.rs"
cpus = 60
ttable_size_kb = 1024
pvtable_size_kb = 64
seed = 1234
blue_random_sample = 2000
reasonable_setups = [1000, 100000]
openings = [20000, 20000, 20000, 10000, 5000, 2000, 1000, 500, 200, 100]
block = 500
log_period_seconds = 60