log = "logs/opening.log"
openings_file = "data/openings.txt"
export_book = "data/book_data.rs"
cpus = 60
ttable_size_kb = 1024
pvtable_size_kb = 64
seed = 1234
blue_random_sample = 2000
reasonable_setups = [1000, 100000]
openings = [10000, 10000, 1000, 100, 10, 1]
block = 500
log_period_seconds = 60