log = "logs/openings2.log"
openings_file = "data/openings2.txt"
export_book = "data/book_data2.rs"
cpus = 60
ttable_size_mb = 64
pvtable_size_mb = 2
seed = 1234
sample_size = 10000
sample_iterations = 5
reasonable_size = 25000
depth = 800
book_size = 10000
extra_depth_book_size = [3500, 1200, 450, 160, 60]
block = 500
log_period_seconds = 60