log = "logs/openings.log"
openings_file = "data/openings.txt"
export_book = "data/book_data.rs"
cpus = 60
ttable_size_mb = 16
pvtable_size_mb = 2
seed = 1234
sample_size = 1000
sample_iterations = 5
reasonable_size = 50000
depth = 500
book_size = 10000
extra_depth_book_size = [3000, 1000]
block = 500
log_period_seconds = 60