log = "logs/self_play.log"

[[command]]
type = "self_play"
output = "data/train5.data"
num_cpus = 60
num_games = 35_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 2
depth = 200
extra_depth = 200
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/test5.data"
num_cpus = 60
num_games = 1_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 2
depth = 200
extra_depth = 200
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"
