log = "data/self_play_7.log"

[[command]]
type = "self_play"
output = "data/train7_0.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_1.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_2.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_3.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_4.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_5.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_6.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_7.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_8.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/train7_9.data"
num_cpus = 60
num_games = 10_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

[[command]]
type = "self_play"
output = "data/test7.data"
num_cpus = 60
num_games = 2_000_000
batch_size = 10_000
ttable_size_mb = 16
pvtable_size_mb = 4
depth = 400
extra_depth = 400
temperature = 0.03
temperature_cutoff = 0.06
features = "WPS"

