log = "logs/self_play.log"

[command.self_play]
output = "data/self_play.cbor"
num_cpus = 30
num_games = 500
batch_size = 500
ttable_size_mb = 32
depth = 4
extra_depth = 4
temperature = 10
temperature_cutoff = 30
