log = "logs/validate.log"

[[command]]
type = "validate"
weights = "data/nnue5a_128_16_partial.weights"
graph_dir = "data"

[command.dataset]
file = "data/test5.data"
features = "WPS"
chunk_size = 4194304
batch_size = 8192
outcome_weight = 0.1

# [command.model.linear]

[command.model.nnue.config]
embedding_size = 128
hidden_sizes = [16]
hidden_weight_bits = 8
value_scale = 10000
