log = "logs/validate.log"

[[command]]
type = "validate"
weights = "data/nnue.weights"

[command.dataset]
file = "data/self_play_test.cbor"
features = "WPS"
value_scale = 1000
chunk_size = 4194304
batch_size = 8192
outcome_weight = 1.0

[command.model.nnue]
max_embedding = 1
embedding_size = 128
hidden_sizes = [8, 32]
hidden_weight_bits = 6
