log = "logs/validate.log"

[[command]]
type = "validate"
weights = "data/nnue6_128_32_32.weights"
graph_dir = "data"

[command.dataset]
file = "data/test6.data"
features = "WPS"
chunk_size = 4194304
batch_size = 8192
outcome_weight = 0.1

# [command.model.linear]

[command.model.nnue.config]
embedding_size = 128
hidden_sizes = [32, 32]
hidden_weight_bits = [8, 6]
value_scale = 10000
