log = "logs/validate.log"

[[command]]
type = "validate"
weights = "data/nnue.weights"
graph_dir = "data"

[command.dataset]
file = "data/test.data"
features = "WPS"
chunk_size = 4194304
batch_size = 8192
outcome_weight = 1.0

# [command.model.linear]

[command.model.nnue.config]
embedding_size = 16
hidden_sizes = []
hidden_weight_bits = 6
value_scale = 10000
