[package]
name = "gui"
edition = "2024"

[dependencies]
wazir-drop = { path = ".." }
extra = { path = "../extra" }

eframe = "0.33.0"
egui_extras = { version = "0.33.0", features = ["svg"] }
log = "0.4.28"
simplelog = "0.12.2"

[lints]
workspace = true