[package]
name = "gui"
edition = "2024"

[dependencies]
wazir-drop = { path = ".." }
extra = { path = "../extra" }

eframe = "0.33.0"
egui_extras = { version = "0.33.0", features = ["svg"] }
rand = "0.9.2"

[lints]
workspace = true