[package]
name = "referee"
edition = "2024"

[dependencies]
wazir-drop = { path = "..", features = ["rand"] }
random-player = { path = "../random-player" }
rand = "0.9.2"
threadpool = "1.8.1"
log = "0.4.28"